const languages = [
  { name: "Technologies", url: "skills/technology.png" },
  { name: "Administration", url: "skills/administration.png" },
  { name: "OS & VM", url: "skills/vmware.png" },
  { name: "Services", url: "skills/service.png" },
  { name: "Applications", url: "skills/office.png" },
  { name: "Support", url: "skills/helpdesk.png" },
  { name: "React JS", url: "skills/react.png" },
  { name: "TypeScript", url: "skills/TypeScript.png" },
  { name: "JavaScript", url: "skills/js.png" },
  { name: "HTML", url: "skills/html.png" },
  { name: "CSS", url: "skills/css.png" },
  { name: "Node JS", url: "skills/nodejs.png" },
  { name: "Express JS", url: "skills/Express.png" },
  { name: "Git", url: "skills/git.png" },
  { name: "MongoDB", url: "skills/mongo.png" },
  { name: "Firebase", url: "skills/firebase.png" },
  { name: "MySQL", url: "skills/mysql.png" },
  { name: "C#", url: "skills/c.png" },
  { name: "Delphi", url: "skills/delphi.png" },
  { name: "Business", url: "skills/audit.png" },
];

const otherSkills = [
  { name: "Thinking", url: "skills/Thinking.png" },
  { name: "Resolution", url: "skills/problem-solving.png" },
  { name: "Planning", url: "skills/Planning.png" },
  { name: "Analytical", url: "skills/analytical.png" },
  { name: "Management", url: "skills/TManagement.png" },
  { name: "LeaderShip", url: "skills/management.png" },
  { name: "Communication", url: "skills/communication.png" },
  { name: "Team Working", url: "skills/Team.png" },
  { name: "Coaching", url: "skills/coaching.png" },
  { name: "Mediation", url: "skills/Conflict.png" },
  { name: "Collaboration", url: "skills/collaboration.png" },
  { name: "Flexibility", url: "skills/flexibility.png" },
  { name: "Negotiation", url: "skills/Negotiation.png" },
  { name: "Timing", url: "skills/Time.png" },
];

const Industry = [
  { name: "SmarTuring", url: "skills/Smart Manufacturing.jpg" },
  { name: "DigitalTwins", url: "skills/Digital-twin.jpg" },
  { name: "Asana", url: "skills/Asana.webp" },
  { name: "Jira", url: "skills/Jira.png" },
  { name: "Microsoft Office 365", url: "skills/365.png" },
  { name: "Industrial Robotics", url: "skills/Robotic.png" },
  { name: "MES", url: "skills/MES.jpg" },
  { name: "CyberPhysics", url: "skills/Cyber Physics.png" },
  { name: "AutoIndustry", url: "skills/Automation.jpg" },
  { name: "ERP", url: "skills/ERP.png" },
  { name: "InduSec", url: "skills/Sybersecurity.jpg" },
  { name: "IIoT", url: "skills/IIoT.png" },
  { name: "Industry 4", url: "skills/Industry 4.png" },
  { name: "Agile", url: "skills/agile.png" },
  { name: "Scrum", url: "skills/scrum.png" },
  { name: "QA & QC", url: "skills/quality.png" },
  { name: "Resource", url: "skills/resource.png" },
  { name: "Stakeholder", url: "skills/stakeholder.png" },
  { name: "Advancement", url: "skills/career.png" },
  { name: "Transformation", url: "skills/Change.png" },
];

export { languages, otherSkills , Industry };
